version: "3"
services:
  frontend:
    image: frontend
    ports:
      - '9000:80'
    networks:
      - ecommerce-app
    restart: always
  backend:
    image: backend
    ports:
      - '8080:5000'
    networks:
      - ecommerce-app
    restart: always
networks:
  ecommerce-app:
    driver: bridge





