PUT http://localhost:5000/api/carts/clean/6267e50e1a5b685f484b8a40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlNTBlMWE1YjY4NWY0ODRiOGEzYyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MTM3NjY5MCwiZXhwIjoxNjUxNTQ5NDkwfQ.o8Bz3YWz_URXQz48grkR5MFa7_rCgwWdaAAq_JIw9_Y