GET http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDc5MjRkZDg5YTU0MjAyNGQ3ODkyNiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0OTM4Njk0OSwiZXhwIjoxNjQ5NTU5NzQ5fQ.zGgGNzxCs9HxWyZ0h0sioOgO9JIxZjtWwh6Ah2BHpdM