GET http://localhost:5000/api/carts/6267e50e1a5b685f484b8a40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlNGYxMWE1YjY4NWY0ODRiOGEzNSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTEzODA4NDgsImV4cCI6MTY1MTU1MzY0OH0.o5GM-Q0gSKoqFd0n2F5l-pjxIHRDo1vzkgI-ENUFjgU