POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "first_name": "Bach",
    "last_name": "Phung",
    "username": "quangbach4",
    "password": "123456789",
    "email": "quangbach4@gmail.com"
}